[package]
name = "tumbleweed"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "4.3.6"
jotdown = "0.2"
minijinja = "0.31.0"
serde = { version="1.0", features=["derive"] }
toml = "0.7"

[profile.release]
strip = true

